POST localhost:3003/obat/kategori/
Content-Type: application/json
Accept: application/json
Authorization: 59eff45e161c65c1f7c26e982ca1c60f359e6a668fc80ac47df04071de0fb436

{
  "nama_kategori_obat" : "balai pantat kuda 3"
}

###
GET localhost:3003/obat/kategori/
Content-Type: application/json
Accept: application/json

###
GET localhost:3003/obat/
Content-Type: application/json
Accept: application/json

###
GET localhost:3003/obat/kategori/count
Content-Type: application/json
Accept: application/json


###
PUT localhost:3003/obat/kategori/5
Content-Type: application/json
Accept: application/json

{
"nama_kategori_obat" : "JAMUR HUFAGRIP 5000"
}

###
DELETE localhost:3003/obat/kategori/4

###
POST localhost:3003/obat/post

### OBAT
POST /obat/post HTTP/1.1
Host: localhost:3003
Content-Length: 537
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="/C:/Users/neko/Documents/Projek/PA/user/tests/file/image.jpg"
Content-Type: image/jpeg

(data)
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="data"
Content-Type: application/json

{
  "kategori_obat" : [1, 2, 3],
  "data_obat" : {
    "nama_obat" : "oryza magenta",
    "dosis_obat" : "sesuai resep dokter",
    "bentuk_sediaan" : "cair",
    "harga" : 50000.0
  }
}

------WebKitFormBoundary7MA4YWxkTrZu0gW--

#################
POST localhost:3003/barang/kategori
Content-Type: application/json
Accept: application/json

{
  "id" : 1,
  "nama_kategori_barang" : "obat jamu"
}

###

POST localhost:3003/barang/kategori
Content-Type: application/json
Accept: application/json

{
  "nama_kategori_barang" : "obat kencur"
}

###

POST localhost:3003/barang/kategori
Content-Type: application/json
Accept: application/json

{
  "nama_kategori_barang" : "obat jahe"
}

###

GET localhost:3003/barang/kategori
Accept: application/json

###

GET localhost:3003/barang/kategori/3
Accept: application/json

###

PUT localhost:3003/barang/kategori/3
Content-Type: application/json
Accept: application/json

{
  "nama_kategori_barang" : "obat baru anak maokma"
}

###

DELETE localhost:3003/barang/kategori/6

##############
POST localhost:3003/barang/
Content-Type: application/json
Accept: application/json

{
  "kategori_barang" : [1,2,3],
  "data_barang" : {
    "nama_obat" : "alat kecantikan 1000",
    "harga" : 50000.0,
    "deskripsi" : "alat kecatikan auto cantik"
  }
}

###

PUT localhost:3003/barang/1
Content-Type: application/json
Accept: application/json

{
  "nama_obat" : "alat kecantikan 1000 oryza p!nk jerman",
  "harga" : 1950000.0,
  "deskripsi" : "alat kecatikan auto cantik forever"
}

###

GET localhost:3003/barang/
Authorization: 490310292d05c57b1eff32097db3de65b5ee837c7874fa106566efbd64e701e8
###

GET localhost:3003/barang/1

###

DELETE localhost:3003/obat/4
Content-Type: application/json
Accept: application/json
Authorization: 59eff45e161c65c1f7c26e982ca1c60f359e6a668fc80ac47df04071de0fb436

######################################

PUT localhost:3003/barang/stok/add
Accept: application/json
Content-Type: application/json

//ObatID      int       `json:"obat_id"`
//Amount      uint      `json:"amount"`
//ExpiredDate time.Time `json:"expired_date"`


{
  "barang_id": 1,
  "amount": 10,
  "expired_date": "19-12-2025"
}

###
PUT localhost:3003/barang/stok/reduce
Accept: application/json
Content-Type: application/json

//ObatID      int       `json:"obat_id"`
//Amount      uint      `json:"amount"`
//ExpiredDate time.Time `json:"expired_date"`


{
  "barang_id": 1,
  "amount": 31,
  "expired_date": "19-12-2025"
}

######################################

PUT localhost:3003/obat/stok/add
Accept: application/json
Content-Type: application/json

//ObatID      int       `json:"obat_id"`
//Amount      uint      `json:"amount"`
//ExpiredDate time.Time `json:"expired_date"`


{
  "obat_id": 1,
  "amount": 10,
  "expired_date": "19-12-2025"
}

###
PUT localhost:3003/obat/stok/reduce
Accept: application/json
Content-Type: application/json

//ObatID      int       `json:"obat_id"`
//Amount      uint      `json:"amount"`
//ExpiredDate time.Time `json:"expired_date"`


{
  "obat_id": 4,
  "amount": 10,
  "expired_date": "19-12-2025"
}