POST localhost:3003/user/signup
Accept: application/json
Content-Type: application/json
Authorization: 2658223ffdea1c2e91af072fe41d7389d4512678893b79c3b62a01f191de1124

{"id":null,"name":"Momon","email":"daadada@dddd.com","password":"babiterbang","role":null}

###
GET localhost:3003/user/list
Accept: application/json
Content-Type: application/json
Authorization: fbf2a9617850ca59c51e2eb96504d7a269d47679fa5ef6a3d109f725301ea2c8

###
GET localhost:3003/user/details/2
Accept: application/json
Content-Type: application/json
Authorization: fbf2a9617850ca59c51e2eb96504d7a269d47679fa5ef6a3d109f725301ea2c8

### RIGHT CREDENTIAL
POST localhost:3003/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password" : "abc123"
}

### WRONG
POST localhost:3003/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "michaelholmes@apotekduma.com",
  "password" : "marjan"
}

### UPDATE TOKEN
POST localhost:3003/auth/logout
Authorization: 0fc4d4857f299c5f037a74b6f98a646c5bd2ff0357ad8dacf3435b32e2a0f52a

###### WHOLE GODDAMN TEST

### LOGIN AGAIN
POST localhost:3003/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "abc123"
}

###
POST localhost:3003/user/signup
Accept: application/json
Content-Type: application/json
Authorization: b3b4176eb57207bb75aff9074861b2052036413d8b9c46d8d77bbca9bb1aee3f

{
"name": "margarethtatchers",
"email": "michaelholmes2@adada.com",
"password" : "martian"
}

### LOGIN AGAIN
POST localhost:3003/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "michaelholmes@apotekduma.com",
  "password": "martian"
}
